version: "3.8"

services:
  25rp18841_exam_web:
    build: .
    container_name: 25rp18841_exam_web
    ports:
      - "8000:80"      
    depends_on:
      - 25rp18841_exam_db
    restart: unless-stopped

  25rp18841_exam_db:
    image: mysql:8.0
    container_name: 25rp18841_exam_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: 25rp18841_exam_shareride_db
    volumes:
      - db-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    restart: unless-stopped

  25rp18841_exam_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 25rp18841_exam_phpmyadmin
    environment:
      PMA_HOST: 25rp18841_exam_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8181:80"
    depends_on:
      - 25rp18841_exam_db
    restart: unless-stopped

volumes:
  db-data:
